[package]
name = "rust_games"
version = "0.1.0"
authors = ["Voovs Selin <Voovs.13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"
dialoguer = "0.5.0"
regex = "1.3.1"
